server:
  port: 19000
spring:
  application:
    name: eureka_vainglory
  security:
    user:
      password: sx96411
      name: vainglory
eureka:
  server:
    enable-self-preservation: false  #关闭自我保护模式
    eviction-interval-timer-in-ms: 4000 #清理间隔，（单位 ms,默认60*1000）
  client:
    service-url:
      defaultZone: http://vainglory:sx96411@localhost:19000/eureka
    prefer-ip-address: true #服务显示的是ip而不是机器名
    register-with-eureka: false #不注册
    fetch-registry: false
